name: Shell Commands 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "My name is Lalit Pratap"
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
            - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
  run-mac-commands:
    runs-on: mac-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash 